server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/stock

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/stock}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

  jackson:
    deserialization:
      fail-on-unknown-properties: true

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /documentation