package com.github.dev.inventory.model.enums;

public enum CategoryType {

    FOOD_AND_DRINKS,
    AUTOMOTIVE,
    BABIES,
    BEAUTY_AND_PERSONAL_CARE,
    BAGS_SUITCASES_AND_BACKPACKS,
    TOYS_AND_GAMES,
    HOME_GARDEN_AND_CLEANING,
    CELL_PHONES_AND_COMMUNICATION,
    COMPUTERS_AND_IT,
    KITCHEN,
    ELECTRONICS_TV_AND_AUDIO,
    SPORTS_ADVENTURE_AND_LEISURE,
    TOOLS_AND_CONSTRUCTION,
    FILMS_SERIES_AND_MUSIC,
    GAMES_AND_CONSOLES,
    BOOKS,
    STATIONERY_AND_OFFICE,
    PET_SHOP,
    CLOTHES_SHOES_AND_ACCESSORIES;

}
